name: CI/CD Docker

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Скачать репозиторий
        uses: actions/checkout@v3

      - name: Логин в Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Сборка Docker образа
        run: |
          docker build -t anonymousdev56/test:latest .

      - name: Push Docker образа в Docker Hub
        run: |
          docker push anonymousdev56/test:latest 
