name: Python CI

on:
  push:
    branches: [ "main" ]

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Скачать репозиторий
        uses: actions/checkout@v3

      - name: Установить Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Запустить main.py
        run: python main.py

      - name: Проверить код
        run: python -m py_compile main.py

      - name: Копировать файл в виртуалку
        uses: appleboy/scp-action@v0.1.4
        with:
          host: "192.168.49.1"
          username: "vbox"
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "main.py"
          target: "/home/vbox/deploy_test/"
